ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email_alerts BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS inapp_alerts BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS reminder_days INTEGER NOT NULL DEFAULT 30;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS theme TEXT NOT NULL DEFAULT 'dark';